import { College } from "@/types/college";

export const colleges: College[] = [
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA (San Francisco Bay Area)",
    avgGPA: 3.96,
    avgSAT: 1505,
    acceptanceRate: 3.7,
    avgCost: 78218,
    ranking: 1,
    studentSize: 17249,
    setting: "suburban",
    majors: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Economics",
      "Mathematics",
      "Physics",
      "Psychology",
    ],
    essays: [
      {
        question: "What matters most to you, and why?",
        wordLimit: 250,
        required: true,
      },
      {
        question: "Tell us about something that is meaningful to you and why.",
        wordLimit: 250,
        required: true,
      },
    ],
    deadline: "January 5, 2026",
  },
  {
    id: "berkeley",
    name: "UC Berkeley",
    location: "Berkeley, CA (San Francisco Bay Area)",
    avgGPA: 3.89,
    avgSAT: 1430,
    acceptanceRate: 14.5,
    avgCost: 43980,
    ranking: 2,
    studentSize: 45057,
    setting: "urban",
    majors: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Economics",
      "Political Science",
      "Mathematics",
      "Psychology",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What would you say is your greatest talent or skill?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "ucla",
    name: "UCLA",
    location: "Los Angeles, CA",
    avgGPA: 3.90,
    avgSAT: 1415,
    acceptanceRate: 12.3,
    avgCost: 36436,
    ranking: 3,
    studentSize: 46430,
    setting: "urban",
    majors: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Psychology",
      "Economics",
      "Political Science",
      "Communications",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "Every person has a creative side. How do you express yours?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "caltech",
    name: "Caltech",
    location: "Pasadena, CA (Los Angeles Area)",
    avgGPA: 3.98,
    avgSAT: 1545,
    acceptanceRate: 3.2,
    avgCost: 79947,
    ranking: 4,
    studentSize: 2397,
    setting: "suburban",
    majors: [
      "Engineering",
      "Physics",
      "Mathematics",
      "Computer Science",
      "Chemistry",
      "Biology",
    ],
    essays: [
      {
        question: "Caltech students enjoy problem-solving. What's a problem you've solved?",
        wordLimit: 200,
        required: true,
      },
      {
        question: "What sparks your curiosity?",
        wordLimit: 200,
        required: true,
      },
    ],
    deadline: "January 3, 2026",
  },
  {
    id: "usc",
    name: "University of Southern California",
    location: "Los Angeles, CA",
    avgGPA: 3.79,
    avgSAT: 1450,
    acceptanceRate: 12.5,
    avgCost: 83448,
    ranking: 5,
    studentSize: 47310,
    setting: "urban",
    majors: [
      "Business",
      "Computer Science",
      "Engineering",
      "Communications",
      "Psychology",
      "Economics",
      "Biology",
    ],
    essays: [
      {
        question: "Describe how you plan to pursue your academic interests at USC.",
        wordLimit: 250,
        required: true,
      },
      {
        question: "Describe yourself in three words.",
        wordLimit: 100,
        required: true,
      },
    ],
    deadline: "January 15, 2026",
  },
  {
    id: "ucsd",
    name: "UC San Diego",
    location: "La Jolla, CA (San Diego Area)",
    avgGPA: 4.08,
    avgSAT: 1380,
    acceptanceRate: 30.2,
    avgCost: 36174,
    ranking: 6,
    studentSize: 42875,
    setting: "suburban",
    majors: [
      "Computer Science",
      "Engineering",
      "Biology",
      "Economics",
      "Psychology",
      "Mathematics",
      "Chemistry",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What have you done to make your school or community a better place?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "uci",
    name: "UC Irvine",
    location: "Irvine, CA (Los Angeles Area)",
    avgGPA: 4.00,
    avgSAT: 1300,
    acceptanceRate: 28.9,
    avgCost: 37635,
    ranking: 7,
    studentSize: 36032,
    setting: "suburban",
    majors: [
      "Computer Science",
      "Engineering",
      "Business",
      "Biology",
      "Psychology",
      "Economics",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What would you say is your greatest talent or skill?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "ucdavis",
    name: "UC Davis",
    location: "Davis, CA (Northern California)",
    avgGPA: 4.03,
    avgSAT: 1290,
    acceptanceRate: 46.3,
    avgCost: 38659,
    ranking: 8,
    studentSize: 39629,
    setting: "suburban",
    majors: [
      "Biology",
      "Engineering",
      "Computer Science",
      "Economics",
      "Psychology",
      "Political Science",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "Every person has a creative side. How do you express yours?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "ucsb",
    name: "UC Santa Barbara",
    location: "Santa Barbara, CA (Southern California)",
    avgGPA: 4.04,
    avgSAT: 1320,
    acceptanceRate: 32.3,
    avgCost: 37879,
    ranking: 9,
    studentSize: 26314,
    setting: "suburban",
    majors: [
      "Computer Science",
      "Engineering",
      "Economics",
      "Biology",
      "Psychology",
      "Communications",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What would you say is your greatest talent or skill?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "pomona",
    name: "Pomona College",
    location: "Claremont, CA (Los Angeles Area)",
    avgGPA: 3.95,
    avgSAT: 1470,
    acceptanceRate: 7.2,
    avgCost: 77957,
    ranking: 10,
    studentSize: 1747,
    setting: "suburban",
    majors: [
      "Economics",
      "Computer Science",
      "Mathematics",
      "Psychology",
      "Biology",
      "Political Science",
    ],
    essays: [
      {
        question: "What do you love about the subject you want to study?",
        wordLimit: 250,
        required: true,
      },
      {
        question: "What do you wish you knew more about?",
        wordLimit: 150,
        required: true,
      },
    ],
    deadline: "January 8, 2026",
  },
  {
    id: "ucr",
    name: "UC Riverside",
    location: "Riverside, CA (Southern California)",
    avgGPA: 3.83,
    avgSAT: 1210,
    acceptanceRate: 66.0,
    avgCost: 36673,
    ranking: 11,
    studentSize: 26809,
    setting: "urban",
    majors: [
      "Business",
      "Biology",
      "Psychology",
      "Engineering",
      "Computer Science",
      "Economics",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What have you done to make your school or community a better place?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "ucsc",
    name: "UC Santa Cruz",
    location: "Santa Cruz, CA (Northern California)",
    avgGPA: 3.76,
    avgSAT: 1250,
    acceptanceRate: 47.7,
    avgCost: 38574,
    ranking: 12,
    studentSize: 19457,
    setting: "suburban",
    majors: [
      "Computer Science",
      "Biology",
      "Psychology",
      "Economics",
      "Engineering",
      "Business",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "Every person has a creative side. How do you express yours?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "ucm",
    name: "UC Merced",
    location: "Merced, CA (Northern California)",
    avgGPA: 3.65,
    avgSAT: 1150,
    acceptanceRate: 85.4,
    avgCost: 36292,
    ranking: 13,
    studentSize: 9191,
    setting: "suburban",
    majors: [
      "Engineering",
      "Biology",
      "Computer Science",
      "Psychology",
      "Business",
    ],
    essays: [
      {
        question: "Describe an example of your leadership experience.",
        wordLimit: 350,
        required: true,
      },
      {
        question: "What would you say is your greatest talent or skill?",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "calpoly",
    name: "Cal Poly San Luis Obispo",
    location: "San Luis Obispo, CA (Central Coast)",
    avgGPA: 4.01,
    avgSAT: 1340,
    acceptanceRate: 30.4,
    avgCost: 30258,
    ranking: 14,
    studentSize: 22013,
    setting: "suburban",
    majors: [
      "Engineering",
      "Business",
      "Computer Science",
      "Biology",
      "Economics",
    ],
    essays: [
      {
        question: "Describe how your experiences have shaped your goals.",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "pepperdine",
    name: "Pepperdine University",
    location: "Malibu, CA (Los Angeles Area)",
    avgGPA: 3.72,
    avgSAT: 1340,
    acceptanceRate: 48.7,
    avgCost: 77768,
    ranking: 15,
    studentSize: 7961,
    setting: "suburban",
    majors: [
      "Business",
      "Communications",
      "Psychology",
      "Economics",
      "Political Science",
    ],
    essays: [
      {
        question: "What excites you about Pepperdine?",
        wordLimit: 250,
        required: true,
      },
    ],
    deadline: "January 15, 2026",
  },
  {
    id: "chapman",
    name: "Chapman University",
    location: "Orange, CA (Los Angeles Area)",
    avgGPA: 3.80,
    avgSAT: 1280,
    acceptanceRate: 54.5,
    avgCost: 73844,
    ranking: 16,
    studentSize: 9850,
    setting: "suburban",
    majors: [
      "Business",
      "Communications",
      "Psychology",
      "Computer Science",
      "Biology",
    ],
    essays: [
      {
        question: "Why are you interested in Chapman?",
        wordLimit: 200,
        required: true,
      },
    ],
    deadline: "January 15, 2026",
  },
  {
    id: "lmu",
    name: "Loyola Marymount University",
    location: "Los Angeles, CA",
    avgGPA: 3.73,
    avgSAT: 1310,
    acceptanceRate: 51.0,
    avgCost: 71367,
    ranking: 17,
    studentSize: 9737,
    setting: "urban",
    majors: [
      "Business",
      "Communications",
      "Psychology",
      "Biology",
      "Economics",
    ],
    essays: [
      {
        question: "Why are you interested in LMU?",
        wordLimit: 300,
        required: true,
      },
    ],
    deadline: "January 15, 2026",
  },
  {
    id: "sdsu",
    name: "San Diego State University",
    location: "San Diego, CA",
    avgGPA: 3.82,
    avgSAT: 1220,
    acceptanceRate: 38.0,
    avgCost: 27828,
    ranking: 18,
    studentSize: 36030,
    setting: "urban",
    majors: [
      "Business",
      "Engineering",
      "Psychology",
      "Biology",
      "Communications",
      "Computer Science",
    ],
    essays: [
      {
        question: "Describe your academic and career goals.",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "sjsu",
    name: "San Jose State University",
    location: "San Jose, CA (San Francisco Bay Area)",
    avgGPA: 3.52,
    avgSAT: 1160,
    acceptanceRate: 67.0,
    avgCost: 24280,
    ranking: 19,
    studentSize: 36208,
    setting: "urban",
    majors: [
      "Engineering",
      "Computer Science",
      "Business",
      "Psychology",
      "Biology",
    ],
    essays: [
      {
        question: "Describe your academic and career goals.",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
  {
    id: "sfsu",
    name: "San Francisco State University",
    location: "San Francisco, CA",
    avgGPA: 3.38,
    avgSAT: 1100,
    acceptanceRate: 72.0,
    avgCost: 24746,
    ranking: 20,
    studentSize: 29586,
    setting: "urban",
    majors: [
      "Business",
      "Psychology",
      "Biology",
      "Communications",
      "Computer Science",
    ],
    essays: [
      {
        question: "Tell us about yourself and your goals.",
        wordLimit: 350,
        required: true,
      },
    ],
    deadline: "November 30, 2025",
  },
];